name: flutter_application_1
description: A student portfolio app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¥ Firebase
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  google_sign_in: ^6.2.1
  firebase_storage: ^13.0.2

  # ðŸ“„ CSV EXPORT
  csv: ^5.0.2
  path_provider: ^2.1.2
  share_plus: ^7.2.1

  # ðŸ“Š Charts
  fl_chart: ^0.66.2

  # ðŸŒ™ Theme + State
  shared_preferences: ^2.2.2
  provider: ^6.0.5

  # ðŸ“„ PDF EXPORT
  pdf: ^3.10.8
  printing: ^5.12.0

  # ðŸŒ HTTP (API calls)
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
